// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr9yIA3V9hkSEvGURh84wsVZykXRNHBA0',
    appId: '1:83804640101:web:a94315aa098cac9746078c',
    messagingSenderId: '83804640101',
    projectId: 'exam-d5185',
    authDomain: 'exam-d5185.firebaseapp.com',
    storageBucket: 'exam-d5185.appspot.com',
    measurementId: 'G-903FF4TK4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaLYIk9VaT1Czb6vBNf_1nKgbvnerfYCE',
    appId: '1:83804640101:android:5930421ae5bbb9b446078c',
    messagingSenderId: '83804640101',
    projectId: 'exam-d5185',
    storageBucket: 'exam-d5185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUbZMZ5qoXa0t7SWhq3FOwfRoaPEFMmk',
    appId: '1:83804640101:ios:06610057c5425d3f46078c',
    messagingSenderId: '83804640101',
    projectId: 'exam-d5185',
    storageBucket: 'exam-d5185.appspot.com',
    iosBundleId: 'com.example.multiUserAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUbZMZ5qoXa0t7SWhq3FOwfRoaPEFMmk',
    appId: '1:83804640101:ios:50fe8626f94f8ce346078c',
    messagingSenderId: '83804640101',
    projectId: 'exam-d5185',
    storageBucket: 'exam-d5185.appspot.com',
    iosBundleId: 'com.example.multiUserAuthentication.RunnerTests',
  );
}
